### ISSUE TITLE
pwys_longi_pibble.csv in OSF didn't have rownames 

### ISSUE THREAD

**Issue by HuaZou** [johannesbjork/Longitudinal-gut-microbiome-changes-in-ICB-treated-advanced-melanoma#1]
Thank you so much. Your work was so excellent, but when I downloaded data from https://osf.io/rakdf/, I found that the pwys_longi_pibble.csv, sgbs_baseline_survival.csv and sgbs_longi_pibble.csv all had no rownames. Therefore, I couldn't reproduce your results by using your codes in this repo.Could you please add the rownames for these files if you are free? 
Thank you in advance.

**Comment by johannesbjork** [comment]
I apologise about this. This should be fixed now.
